// <auto-generated />
using CalculatorWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculatorWebApplication.Migrations
{
    [DbContext(typeof(CalculatorAppDbContext))]
    partial class CalculatorAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculatorWebApplication.Models.CalculatorC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("operand1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("operand2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("result")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("calculator");
                });
#pragma warning restore 612, 618
        }
    }
}
